### ISSUE TITLE
Permission denied: 'prodigal'

### ISSUE THREAD

**Issue by zhichusun** [oschwengers/platon#27]
Hi!
Traceback (most recent call last):
  File "/root/miniconda3/envs/platon/bin/platon", line 10, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/platon/lib/python3.8/site-packages/platon/platon.py", line 60, in main
    pu.test_dependencies()  # test dependencies
  File "/root/miniconda3/envs/platon/lib/python3.8/site-packages/platon/utils.py", line 125, in test_dependencies
    version = read_tool_output(dependency)
  File "/root/miniconda3/envs/platon/lib/python3.8/site-packages/platon/utils.py", line 66, in read_tool_output
    tool_output = str(sp.check_output(command, stderr=sp.STDOUT)) # stderr must be added in case the tool output is not piped into stdout
  File "/root/miniconda3/envs/platon/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/root/miniconda3/envs/platon/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/root/miniconda3/envs/platon/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/miniconda3/envs/platon/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'prodigal'

It keeps showing no permission, why is this? I am a beginner hope someone can help me, thank you very much

**Comment by zhichusun** [comment]
Sorry I found the reason is that there is no permission to change the file, the software is very good and there is no problem.
